#pragma once

#cmakedefine PROJECT "@PROJECT@"

#cmakedefine PROJECT_VERSION "@PROJECT_VERSION@"

#cmakedefine PROJECT_VERSION_MAJOR @PROJECT_VERSION_MAJOR@

#cmakedefine PROJECT_VERSION_MINOR @PROJECT_VERSION_MINOR@

#cmakedefine PROJECT_VERSION_PATCH @PROJECT_VERSION_PATCH@

#cmakedefine MAX_NUMBER_OF_AGENTS @MAX_NUMBER_OF_AGENTS@

#ifndef PROJECT_VERSION_MAJOR
#define PROJECT_VERSION_MAJOR 0
#endif

#ifndef PROJECT_VERSION_MINOR
#define PROJECT_VERSION_MINOR 0
#endif

#ifndef PROJECT_VERSION_PATCH
#define PROJECT_VERSION_PATCH 0
#endif

@OPENSSL_DEFINE@
